const BACKEND_BASE="/.netlify/functions/proxy"; const AUTO_REFRESH_MS=120000;
const KEY_TOKEN='auth_token',KEY_DEVICE='device_id',KEY_DARK='dark_mode';
const gateEl=document.getElementById('gate'),mainEl=document.getElementById('main'); const codeInput=document.getElementById('codeInput'),redeemBtn=document.getElementById('redeemBtn'),gateMsg=document.getElementById('gateMsg');
const tabs=Array.from(document.querySelectorAll('.tab')); const newsPane=document.getElementById('news'),signalsPane=document.getElementById('signals'),annPane=document.getElementById('ann');
const refreshBtn=document.getElementById('refreshBtn'),updatedAtEl=document.getElementById('updatedAt'); const darkToggle=document.getElementById('darkToggle'),copy24hBtn=document.getElementById('copy24hBtn'),copyMsg=document.getElementById('copyMsg');
let refreshTimer=null; function setVisible(el,v){el.classList.toggle('hidden',!v);} function fmtDate(dt){const d=new Date(dt);return isNaN(d)?'':d.toLocaleString();}
function h(t){const d=document.createElement('div');d.textContent=t??'';return d.innerHTML;} function save(k,v){localStorage.setItem(k,JSON.stringify(v));} function load(k,d){try{return JSON.parse(localStorage.getItem(k))??d;}catch{return d;}}
async function apiRedeem(code,deviceId){const res=await fetch(`${BACKEND_BASE}?path=redeem&code=${encodeURIComponent(code)}&deviceId=${encodeURIComponent(deviceId)}`);return res.json();}
async function apiFeed(type,token){const res=await fetch(`${BACKEND_BASE}?path=feed&type=${encodeURIComponent(type)}&token=${encodeURIComponent(token)}`);return res.json();}
function renderNews(items){newsPane.innerHTML='';if(!items?.length){newsPane.innerHTML='<p class="small">No items yet.</p>';return;}items.forEach(it=>{const d=document.createElement('div');d.className='item';const tags=[];if(it.tag)tags.push(h(it.tag));if(String(it.pinned).toUpperCase()==='TRUE')tags.push('Pinned');const badges=tags.map(t=>`<span class="badge">${t}</span>`).join(' ');const link=it.link?` <a href="${h(it.link)}" target="_blank" rel="noreferrer">link</a>`:'';d.innerHTML=`<div><strong>${h(it.title)}</strong> ${badges}</div><div class="small">${h(it.ts)}</div><div>${h(it.body)}</div><div>${link}</div>`;newsPane.appendChild(d);});}
function renderSignals(items){const list=document.getElementById('signalsList');list.innerHTML='';if(!items?.length){list.innerHTML='<p class="small">No signals yet.</p>';return;}items.forEach(it=>{const d=document.createElement('div');d.className='item';const badges=String(it.pinned).toUpperCase()==='TRUE'?`<span class="badge">Pinned</span>`:'';d.innerHTML=`<div><strong>${h(it.pair)}</strong> — ${h(it.action)} ${badges}</div><div class="small">${h(it.ts)}</div><div>Entry: ${h(it.entry)} | TP: ${h(it.tp)} | SL: ${h(it.sl)}</div><div>${h(it.notes)}</div>`;list.appendChild(d);});}
function renderAnnouncements(fromNews){annPane.innerHTML='';const anns=(fromNews||[]).filter(it=>{const t=(it.tag||'').toString().trim().toUpperCase();return t==='ANN'||t==='ANNOUNCE'||t==='ANNOUNCEMENT';});if(!anns.length){annPane.innerHTML='<p class="small">No announcements. Tag news as ANN to show here.</p>';return;}anns.forEach(it=>{const d=document.createElement('div');d.className='item';const badges=String(it.pinned).toUpperCase()==='TRUE'?`<span class="badge">Pinned</span>`:'';const link=it.link?` <a href="${h(it.link)}" target="_blank" rel="noreferrer">link</a>`:'';d.innerHTML=`<div><strong>${h(it.title)}</strong> ${badges}</div><div class="small">${h(it.ts)}</div><div>${h(it.body)}</div><div>${link}</div>`;annPane.appendChild(d);});}
function copyLast24hSignals(items){const now=Date.now(),dayAgo=now-86400000;const fresh=(items||[]).filter(it=>{const t=new Date(it.ts).getTime();return!isNaN(t)&&t>=dayAgo;});if(!fresh.length)return'';return fresh.map(it=>`[${it.ts}] ${it.pair} ${it.action} | Entry: ${it.entry} | TP: ${it.tp} | SL: ${it.sl} | ${it.notes||''}`.trim()).join('\n');}
async function showMain(){setVisible(gateEl,false);setVisible(mainEl,true);await doRefresh();if(refreshTimer)clearInterval(refreshTimer);refreshTimer=setInterval(doRefresh,AUTO_REFRESH_MS);}
async function doRefresh(){const token=load(KEY_TOKEN,null);if(!token)return;try{const [news,sig]=await Promise.all([apiFeed('news_orders',token),apiFeed('signals',token)]);if(news?.items){renderNews(news.items);renderAnnouncements(news.items);}if(sig?.items){renderSignals(sig.items);copy24hBtn.onclick=async()=>{const txt=copyLast24hSignals(sig.items);if(!txt){copyMsg.textContent='No signals in last 24h.';return;}await navigator.clipboard.writeText(txt);copyMsg.textContent='Copied!';setTimeout(()=>copyMsg.textContent='',2000);};}updatedAtEl.textContent=fmtDate(new Date());}catch(e){updatedAtEl.textContent='refresh failed';}}
(function init(){const isDark=load(KEY_DARK,(window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches));document.documentElement.classList.toggle('dark',!!isDark);darkToggle.textContent=document.documentElement.classList.contains('dark')?'☀️':'🌙';darkToggle.onclick=()=>{const d=!document.documentElement.classList.contains('dark');document.documentElement.classList.toggle('dark',d);darkToggle.textContent=d?'☀️':'🌙';save(KEY_DARK,d);};let deviceId=load(KEY_DEVICE,null);if(!deviceId){deviceId=uuidv4();save(KEY_DEVICE,deviceId);}const token=load(KEY_TOKEN,null);if(token){showMain();}else{setVisible(gateEl,true);setVisible(mainEl,false);}redeemBtn.addEventListener('click',async()=>{gateMsg.textContent='';const code=(codeInput.value||'').trim();if(!code){gateMsg.textContent='Enter a code.';return;}redeemBtn.disabled=true;try{const res=await apiRedeem(code,deviceId);if(res.ok&&res.token){save(KEY_TOKEN,res.token);showMain();}else{gateMsg.textContent=res.error||'Failed to redeem code.';redeemBtn.disabled=false;}}catch(e){gateMsg.textContent='Network error.';redeemBtn.disabled=false;}});tabs.forEach(btn=>{btn.addEventListener('click',()=>{tabs.forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.tabpane').forEach(p=>p.classList.add('hidden'));document.getElementById(btn.dataset.tab).classList.remove('hidden');});});refreshBtn.addEventListener('click',doRefresh);})();